#ifndef LEPTRINO_FORCE_TORQUE_SENSOR__VISIBILITY_CONTROL_HPP_
#define LEPTRINO_FORCE_TORQUE_SENSOR__VISIBILITY_CONTROL_HPP_

// This logic was borrowed (then namespaced) from the examples on the gcc wiki:
//     https://gcc.gnu.org/wiki/Visibility

#if defined _WIN32 || defined __CYGWIN__
#ifdef __GNUC__
#define LEPTRINO_FORCE_TORQUE_SENSOR_EXPORT __attribute__((dllexport))
#define LEPTRINO_FORCE_TORQUE_SENSOR_IMPORT __attribute__((dllimport))
#else
#define LEPTRINO_FORCE_TORQUE_SENSOR_EXPORT __declspec(dllexport)
#define LEPTRINO_FORCE_TORQUE_SENSOR_IMPORT __declspec(dllimport)
#endif
#ifdef LEPTRINO_FORCE_TORQUE_SENSOR_BUILDING_LIBRARY
#define LEPTRINO_FORCE_TORQUE_SENSOR_PUBLIC LEPTRINO_FORCE_TORQUE_SENSOR_EXPORT
#else
#define LEPTRINO_FORCE_TORQUE_SENSOR_PUBLIC LEPTRINO_FORCE_TORQUE_SENSOR_IMPORT
#endif
#define LEPTRINO_FORCE_TORQUE_SENSOR_PUBLIC_TYPE LEPTRINO_FORCE_TORQUE_SENSOR_PUBLIC
#define LEPTRINO_FORCE_TORQUE_SENSOR_LOCAL
#else
#define LEPTRINO_FORCE_TORQUE_SENSOR_EXPORT __attribute__((visibility("default")))
#define LEPTRINO_FORCE_TORQUE_SENSOR_IMPORT
#if __GNUC__ >= 4
#define LEPTRINO_FORCE_TORQUE_SENSOR_PUBLIC __attribute__((visibility("default")))
#define LEPTRINO_FORCE_TORQUE_SENSOR_LOCAL __attribute__((visibility("hidden")))
#else
#define LEPTRINO_FORCE_TORQUE_SENSOR_PUBLIC
#define LEPTRINO_FORCE_TORQUE_SENSOR_LOCAL
#endif
#define LEPTRINO_FORCE_TORQUE_SENSOR_PUBLIC_TYPE
#endif

#endif  // LEPTRINO_FORCE_TORQUE_SENSOR_SENSOR__VISIBILITY_CONTROL_HPP_
